apiVersion: example.com/v1
kind: TransientRoleBinding
metadata:
  name: test2
  namespace: metacontroller-webhooks
validFrom: 2023-04-04T17:10:00Z
validUntil: 2023-04-04T17:20:00Z
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-deletor
subjects:
- kind: ServiceAccount
  name: trb-sa@abobrovnikov-2921401a.iam.gserviceaccount.com
