apiVersion: example.com/v1
kind: TransientRoleBinding
metadata:
  name: test2
  namespace: metacontroller-webhooks
validFrom: 2023-04-03T21:55:00Z
validUntil: 2023-04-03T22:15:00Z
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-deletor
subjects:
- kind: User
  name: esmelser@apexfintechsolutions.com
