apiVersion: example.com/v1
kind: TransientRoleBinding
metadata:
  name: test1
  namespace: default
validFrom: 2023-04-03T21:07:00Z
validUntil: 2023-04-03T21:15:00Z
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: User
  name: apex-anthonybob
